POST http://localhost:3000/api/sauces 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDVhMjM0OTE2NjJhNzE0ODA5NWE3Y2IiLCJpYXQiOjE2MTY1MjAwNDMsImV4cCI6MTYxNjYwNjQ0M30.E3C-UFWPOR-n-urmDZdK1oVfaZ7jDdMVR73WWS8YR80

{
    "_id": "okok",
    "name": "antoine",
    "manufacturer": "antoine",
    "description": "antoine",
    "mainPepper": "antoine",
    "imageUrl": "antoine",
    "heat": 1,
    "userId": "605a23491662a7148095a7cb"
}

### 

POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "nicolas2556@test.frr", 
    "password": "12Op1drfrfr"
}

### 

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "nicolas2556@test.frr", 
    "password": "12Op1drfrfr"
}

### 
GET http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDZkYTk3OTM4NDIzNTM4MzhkODhiODEiLCJpYXQiOjE2MTc4MDA1NjQsImV4cCI6MTYxNzg4Njk2NH0.wj3Ilv8RAaU0teOvKQ9bdL4e4-_W1ey1zcM4YhQk10E

### 

PUT http://localhost:3000/api/sauces/606db83daeb08f3d9c048127
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDZkYTk3OTM4NDIzNTM4MzhkODhiODEiLCJpYXQiOjE2MTc4MDMzMDgsImV4cCI6MTYxNzg4OTcwOH0.wb1ivMQ8aCZEryROCQ03lFX68KeFR8-aFOf6SQv6aCA

{ 
    "likes": "0",
    "name": "changerlasauce2",
    "manufacturer": "changerlasauce",
    "description": "changerlasauce"
}

###
DELETE http://localhost:3000/api/sauces/606db83daeb08f3d9c048127
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDZkYTk3OTM4NDIzNTM4MzhkODhiODEiLCJpYXQiOjE2MTc4MDMzMDgsImV4cCI6MTYxNzg4OTcwOH0.wb1ivMQ8aCZEryROCQ03lFX68KeFR8-aFOf6SQv6aCA

